sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_4a01973f5260_key -iv $encrypted_4a01973f5260_iv -in focal-column-250714-43c022a8c0a2.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project focal-column-250714
  - gcloud config set compute/zone us-east1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME --pasword-stdin"
  - docker build -t mwiesbau/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mwiesbau/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
