sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_4a01973f5260_key -iv $encrypted_4a01973f5260_iv -in focal-column-250714-43c022a8c0a2.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project  multi-k8s focal-column-250714
  - gckoud config set compute/zone us-east1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME --pasword-stdin"
