apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-wiesbauer-me-tls
spec:
  secretName: k8s-mwiesbauer-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.wiesbauer.me
  dnsNames:
    - k8s.wiesbauer.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.wiesbauer.me
